Update cmake-multi-platform.yml

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -48,8 +48,15 @@ jobs:
 
     - name: Debug CMake Variables
       run: |
-       echo "CMAKE_PREFIX_PATH: /usr/lib/x86_64-linux-gnu/cmake/Qt6"
-       echo "Qt6_DIR: /usr/lib/x86_64-linux-gnu/cmake/Qt6"
+       echo "$CMAKE_PREFIX_PATH"
+       echo "$Qt6_DIR"
+
+    - name: Verify Qt6 Installation
+      run: |
+       if [ ! -f /usr/lib/x86_64-linux-gnu/cmake/Qt6/Qt6Config.cmake ]; then
+        echo "Qt6Config.cmake not found. Ensure that Qt6 is installed correctly."
+        exit 1
+       fi
 
     - name: Set reusable strings
       id: strings
@@ -61,6 +68,8 @@ jobs:
       env:
         CMAKE_PREFIX_PATH: /usr/lib/x86_64-linux-gnu/cmake/Qt6
         Qt6_DIR: /usr/lib/x86_64-linux-gnu/cmake/Qt6
+        echo "CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH"
+        echo "Qt6_DIR: $Qt6_DIR"
       run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
